
action:

  state:
    method: "filesystem"
    params:
      root_path: "/tmp/tpas"
    calls:
      ttl_seconds: 7200
    tasks:
      ttl_seconds: 7200

  credentials:
    # Bearer Token: exampleuser01.test-secret-CHANGE-ME-PLEASE-alphanumeric
    exampleuser01:  # NB: the 'exampleuser01' key-name is hardcoded to be prevented when non-debug mode.
      secret: test-secret-CHANGE-ME-PLEASE-alphanumeric
      tags:
        comment: "User 12345 from the Foo system"
        other_data: "This is a free-form tag value"
        other_system_name: foo
        other_system_user_id: 12345
