
action:

  state:
    method: "filesystem"
    params:
      root_path: "/tmp/tpas"
    calls:
      ttl_seconds: 7200
    tasks:
      ttl_seconds: 7200

  cli: {}

  api: {}

  credentials:
    # auth_token == internal-microservice.demo-secret-CHANGE-ME-PLEASE-alphanumeric
    internal-microservice:
      secret: demo-secret-CHANGE-ME-PLEASE-alphanumeric
      tags:
        comment: "User 12345 from the Foo system"
        other_data: "This is a free-form tag value"
        other_system_name: foo
        other_system_user_id: 12345
